name: emr_app
description: "A new Flutter project for Medical Records."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # المكتبات الأساسية للبيانات المحلية
  sqflite: ^2.3.0
  path: ^1.9.0
  
  # مكتبة تخزين بيانات الدخول
  shared_preferences: ^2.2.0
  
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
